#!/bin/bash

echo ""
echo "=================================="
echo "🎉 Home Hub Development Container"
echo "=================================="
echo ""
echo "📝 Quick Start Commands:"
echo "  pnpm dev              Start development server (http://localhost:3000)"
echo "  pnpm build            Build for production"
echo "  pnpm lint             Run ESLint"
echo "  pnpm format           Format code with Prettier"
echo "  pnpm typecheck        Check TypeScript types"
echo "  pnpm code-quality     Run full quality check"
echo ""
echo "🗄️  Database Commands:"
echo "  pnpm db:gen           Generate Prisma client"
echo "  pnpm db:push          Push schema changes to database"
echo "  pnpm db:studio        Open Prisma Studio (http://localhost:5555)"
echo ""
echo "💾 Files Shared:"
echo "  ~/Downloads → /downloads (bidirectional mount)"
echo ""
echo "✨ VS Code Extensions Installed:"
echo "  • ESLint, Prettier, Tailwind CSS"
echo "  • Prisma, MongoDB"
echo "  • Python, GitLens, GitHub Copilot"
echo ""
echo "🚀 Ready to code! Run 'pnpm dev' to start developing."
echo ""
